name: Build Android files with Gradle
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  buildWithGradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./SeQR
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    - name: Build with Gradle
      run: gradle build
    #- name: Run Unit Tests
      #run: ./gradlew test
